version: '3'

services:
  app:
    build: .
    ports:
      - "8081"  # Use dynamic port assignment for one instance
    depends_on:
      - redis

  app_2:
    build: .
    ports:
      - "8082:8081"  # Explicitly bind the second instance to port 8082
    depends_on:
      - redis

  init_redis:
    image: python:3.8-slim
    volumes:
      - ./initial_data_load.py:/app/initial_data_load.py:ro
    command: ["sh", "-c", "pip install redis && python /app/initial_data_load.py"]
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app_2
